CREATE TABLE perfil
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    telefone VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_perfil PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    telefone VARCHAR(255),
    email    VARCHAR(255),
    role     VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);